default:
  tags:
    - kubernetes
    
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
 - deploy_windows
 - deploy_osx
 - test

sast:
  variables:
    SEARCH_MAX_DEPTH: 10
    SECURE_LOG_LEVEL: "debug"
    
Deploy Windows:
  stage: deploy_windows
  script:
    - call src/build.bat
  tags:
    - windows 
  artifacts:
    paths:
       - ./src/Bin/Windows-x64/FBuild.exe
       - ./src/Bin/Windows-x64/FBuildWorker.exe
    expire_in: 3 days
   
Deploy OSX:   
  stage: deploy_osx
  script:
    - bash src/MacOSX_build_release.sh
  tags:
    - osx 
  artifacts:
    paths:
       - ./src/Bin/MacOSX-x64/FBuild
       - ./src/Bin/MacOSX-x64/FBuildWorker
    expire_in: 3 days